#!/bin/bash

workdir=$(dirname "$0")
echo $workdir
tracked=$workdir/'tracked.txt'

if [ ! -e $tracked ]; then
	echo 'tracked.txt is missing.'
	exit
fi

if [ ! -d $dest ]; then
	mkdir $dest
fi

lastchar=$(tail -c 1 $tracked)
lastchar=$(printf "%d" "'$lastchar")
if [[ ! ($lastchar -eq 0 || $lastchar -eq 10) ]]; then
	echo '' >> $tracked
fi

input="$tracked"
while IFS= read -r line
do
	# limpa espaços da  linha
	line=$(echo $line | awk '{$line=$line;print}')
	if [[ $line == "" ]]; then
		continue
	fi
	
	first_char=${line:0:1}	
	if [[ $first_char == "#" ]]; then
		continue
	fi

	args=($line)
	source=${args[0]}

	if [[ ${#args[@]} -gt 1 ]];then 
		dest=${args[1]}
	else
		dest=$(basename $source)
	fi
		echo $dest

	destdir=$(dirname $dest)
	if [[ ! -d $destdir ]]; then
		mkdir -p $(dirname $dest) 
	fi

	source=$(eval echo $source)
	
	cp -u $source $workdir/$dest
	if [[ $? -eq 0 ]]; then
		echo 'Updated '$dest' from '$source
	else
		echo 'Failed to update '$source
	fi
done < "$input"
