#!/bin/bash

tracked=$PWD/'tracked.txt'
dest=$PWD/'files'

if [ ! -e $tracked ]; then
	echo 'tracked.txt is missing.'
	exit
fi

if [ ! -d $dest ]; then
	mkdir $dest
fi

lastchar=$(tail -c 1 $tracked)
lastchar=$(printf "%d" "'$lastchar")
if [[ ! ($lastchar -eq 0 || $lastchar -eq 10) ]]; then
	echo '' >> $tracked
fi

input="$tracked"
while IFS= read -r line
do
	line=$(echo $line | awk '{$line=$line;print}')
	
	first_char=${line:0:1}	
	if [[ $first_char == "#" ]]; then
		continue
	fi

	args=($line)
	source=${args[0]}

	if [[ ${#args[@]} -gt 1 ]];then 
		dest_name=${args[1]}
	else
		dest_name=$(basename $source)
	fi

	source=$(eval echo $source)
	
	cp -u $source $dest/$dest_name
	if [[ $? -eq 0 ]]; then
		echo 'Updated '$dest_name' from '$source
	else
		echo 'Failed to update '$source
	fi
done < "$input"
